[package]
name = "osprey_zulip"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "0.32.1"
scraper = "0.19.1"
roc_parse = { path = "../../../roc-lang/roc/crates/compiler/parse" }
bumpalo = { version = "3.12.0", features = ["collections"] }
